name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup JBang
        uses: jbangdev/setup-jbang@main

      - name: Run Tests
        run: |
          jbang run BtrfsBackupTest.java

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './TEST-*.xml'

      - name: Build JAR package
        run: |
          jbang export portable BtrfsBackup.java

      - name: Build binary package
        run: |
          jbang export native BtrfsBackup.java

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: BtrfsBackup.jar
          path: BtrfsBackup.jar

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: BtrfsBackup
          path: BtrfsBackup

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            BtrfsBackup.java
            BtrfsBackup.jar
            BtrfsBackup
